"""Build embed.js, which puts the calculator into a blog post.

Run: python3 build_embed.py [base-url]
Writes embed.js from index.html. Run it after every change to index.html (test_calc.py fails if
embed.js is stale). With a base URL (where embed.js, data.js and app.js are hosted) it also prints
the two lines to paste into the post's HTML view. Because embed.js carries the markup and styles,
the post never needs editing after a release.
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))


def embed_js():
    with open(os.path.join(HERE, "index.html"), encoding="utf-8") as f:
        src = f.read()
    style = re.search(r'<style id="wtcalc-style">.*?</style>', src, re.S).group(0)
    markup = re.search(r'<main id="wtcalc">(.*?)</main>', src, re.S).group(1)
    return f"""// Generated by build_embed.py from index.html; do not edit by hand.
// Fills <div id="wtcalc"></div> with the calculator, then loads data.js and app.js from
// the same place this file was loaded from.
(() => {{
  const base = document.currentScript.src.replace(/[^/]*$/, "");
  document.head.insertAdjacentHTML("beforeend", {json.dumps(style, ensure_ascii=False)});
  document.getElementById("wtcalc").innerHTML = {json.dumps(markup, ensure_ascii=False)};
  const load = (file, next) => {{
    const s = document.createElement("script");
    s.src = base + file;
    s.onload = next;
    document.body.appendChild(s);
  }};
  load("data.js", () => load("app.js"));
}})();
"""


def post_snippet(base):
    return f'<div id="wtcalc"></div>\n<script src="{base.rstrip("/")}/embed.js"></script>\n'


def main():
    with open(os.path.join(HERE, "embed.js"), "w", encoding="utf-8") as f:
        f.write(embed_js())
    print("wrote embed.js")
    if len(sys.argv) > 1:
        print("\nPaste into the post's HTML view:\n")
        print(post_snippet(sys.argv[1]))


if __name__ == "__main__":
    main()
