"""Build ../blogger/post.html, the snippet to paste into a Blogger post's HTML view.

Run: python3 build_embed.py https://cdn.jsdelivr.net/gh/<github-user>/<repo>@<tag>/wt-calc
The URL is where data.js and app.js are hosted; without it a placeholder is written.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PLACEHOLDER = "https://cdn.jsdelivr.net/gh/GITHUB_USER/REPO@TAG/wt-calc"


def snippet(base):
    with open(os.path.join(HERE, "index.html"), encoding="utf-8") as f:
        src = f.read()
    style = re.search(r'<style id="wtcalc-style">.*?</style>', src, re.S).group(0)
    main = re.search(r'<main id="wtcalc">(.*?)</main>', src, re.S).group(1)
    return (
        "<!-- War Thunder research calculator. Generated by wt-calc/build_embed.py; edit index.html instead. -->\n"
        f'{style}\n<div id="wtcalc">{main}</div>\n'
        f'<script src="{base}/data.js"></script>\n<script src="{base}/app.js"></script>\n'
    )


def main():
    base = sys.argv[1].rstrip("/") if len(sys.argv) > 1 else PLACEHOLDER
    out = os.path.join(HERE, "..", "blogger", "post.html")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write(snippet(base))
    print(f"wrote {os.path.normpath(out)} (scripts from {base})")


if __name__ == "__main__":
    main()
